# Generated by Django 3.2.5 on 2022-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('classid', models.ManyToManyField(to='classes.Classes')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
