# Generated by Django 3.2.5 on 2022-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teacher', '0002_auto_20220121_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classid',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classid',
            field=models.ManyToManyField(to='classes.Classes'),
        ),
    ]
