# Generated by Django 3.2.5 on 2022-01-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teacher', '0003_auto_20220121_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classid',
            field=models.ManyToManyField(related_name='clas', to='classes.Classes'),
        ),
    ]
