# Generated by Django 3.2.5 on 2022-01-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_classid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classid',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classid',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
