# Generated by Django 3.2.5 on 2022-01-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, unique=True)),
                ('contact_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('classid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
